//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CateringCalculator.Resources.Internationalization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CateringCalculator.Resources.Resources.Internationalization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // The following properties were copied from the UI-generated designer and made public.
        // Add more properties if the build reports missing members.

        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }

        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }

        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }

        public static string Button_Details {
            get {
                return ResourceManager.GetString("Button_Details", resourceCulture);
            }
        }

        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }

        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }

        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }

        public static string DeleteModal_IngredientMessage {
            get {
                return ResourceManager.GetString("DeleteModal_IngredientMessage", resourceCulture);
            }
        }

        public static string DeleteModal_IngredientTitle {
            get {
                return ResourceManager.GetString("DeleteModal_IngredientTitle", resourceCulture);
            }
        }

        public static string DeleteModal_RecipeMessage {
            get {
                return ResourceManager.GetString("DeleteModal_RecipeMessage", resourceCulture);
            }
        }

        public static string DeleteModal_RecipeTitle {
            get {
                return ResourceManager.GetString("DeleteModal_RecipeTitle", resourceCulture);
            }
        }

        // Additional UI keys referenced across the UI. Add more here as build reports missing members.
        public static string Nav_Overview { get { return ResourceManager.GetString("Nav_Overview", resourceCulture); } }
        public static string Nav_EventPlanner { get { return ResourceManager.GetString("Nav_EventPlanner", resourceCulture); } }
        public static string Nav_Recipes { get { return ResourceManager.GetString("Nav_Recipes", resourceCulture); } }
        public static string Nav_Ingredients { get { return ResourceManager.GetString("Nav_Ingredients", resourceCulture); } }

        public static string Home_Title { get { return ResourceManager.GetString("Home_Title", resourceCulture); } }
        public static string Home_Subtitle { get { return ResourceManager.GetString("Home_Subtitle", resourceCulture); } }
        public static string Home_Intro { get { return ResourceManager.GetString("Home_Intro", resourceCulture); } }
        public static string Home_UsageTitle { get { return ResourceManager.GetString("Home_UsageTitle", resourceCulture); } }
        public static string Home_Usage_Step1 { get { return ResourceManager.GetString("Home_Usage_Step1", resourceCulture); } }
        public static string Home_Usage_Step2 { get { return ResourceManager.GetString("Home_Usage_Step2", resourceCulture); } }
        public static string Home_Usage_Step3 { get { return ResourceManager.GetString("Home_Usage_Step3", resourceCulture); } }
        public static string Home_Note { get { return ResourceManager.GetString("Home_Note", resourceCulture); } }

        public static string Recipes_Title { get { return ResourceManager.GetString("Recipes_Title", resourceCulture); } }
        public static string Recipes_Subtitle { get { return ResourceManager.GetString("Recipes_Subtitle", resourceCulture); } }
        public static string Recipes_IngredientsHeader { get { return ResourceManager.GetString("Recipes_IngredientsHeader", resourceCulture); } }
        public static string Recipes_UnknownIngredient { get { return ResourceManager.GetString("Recipes_UnknownIngredient", resourceCulture); } }
        public static string Recipes_CostPerDrink { get { return ResourceManager.GetString("Recipes_CostPerDrink", resourceCulture); } }

        public static string Ingredients_Title { get { return ResourceManager.GetString("Ingredients_Title", resourceCulture); } }
        public static string Ingredients_Subtitle { get { return ResourceManager.GetString("Ingredients_Subtitle", resourceCulture); } }

        public static string Event_Subtitle { get { return ResourceManager.GetString("Event_Subtitle", resourceCulture); } }

        public static string PersonnelModal_DefaultRole { get { return ResourceManager.GetString("PersonnelModal_DefaultRole", resourceCulture); } }
        public static string PersonnelModal_Title { get { return ResourceManager.GetString("PersonnelModal_Title", resourceCulture); } }
        public static string PersonnelModal_RolePlaceholder { get { return ResourceManager.GetString("PersonnelModal_RolePlaceholder", resourceCulture); } }
        public static string PersonnelModal_CountHeader { get { return ResourceManager.GetString("PersonnelModal_CountHeader", resourceCulture); } }
        public static string PersonnelModal_HoursHeader { get { return ResourceManager.GetString("PersonnelModal_HoursHeader", resourceCulture); } }
        public static string PersonnelModal_RateHeader { get { return ResourceManager.GetString("PersonnelModal_RateHeader", resourceCulture); } }
        public static string PersonnelModal_AddPosition { get { return ResourceManager.GetString("PersonnelModal_AddPosition", resourceCulture); } }
        public static string PersonnelModal_Total { get { return ResourceManager.GetString("PersonnelModal_Total", resourceCulture); } }

        public static string FixedModal_DefaultDescription { get { return ResourceManager.GetString("FixedModal_DefaultDescription", resourceCulture); } }

        // Recipe modal keys
        public static string RecipeModal_TitleEdit { get { return ResourceManager.GetString("RecipeModal_TitleEdit", resourceCulture); } }
        public static string RecipeModal_TitleNew { get { return ResourceManager.GetString("RecipeModal_TitleNew", resourceCulture); } }
        public static string RecipeModal_NameLabel { get { return ResourceManager.GetString("RecipeModal_NameLabel", resourceCulture); } }
        public static string RecipeModal_NamePlaceholder { get { return ResourceManager.GetString("RecipeModal_NamePlaceholder", resourceCulture); } }
        public static string RecipeModal_DescLabel { get { return ResourceManager.GetString("RecipeModal_DescLabel", resourceCulture); } }
        public static string RecipeModal_DescPlaceholder { get { return ResourceManager.GetString("RecipeModal_DescPlaceholder", resourceCulture); } }
        public static string RecipeModal_IngredientsHeader { get { return ResourceManager.GetString("RecipeModal_IngredientsHeader", resourceCulture); } }
        public static string RecipeModal_EmptyWarning { get { return ResourceManager.GetString("RecipeModal_EmptyWarning", resourceCulture); } }
        public static string RecipeModal_TableIngredient { get { return ResourceManager.GetString("RecipeModal_TableIngredient", resourceCulture); } }
        public static string RecipeModal_TableAmount { get { return ResourceManager.GetString("RecipeModal_TableAmount", resourceCulture); } }
        public static string RecipeModal_TableAction { get { return ResourceManager.GetString("RecipeModal_TableAction", resourceCulture); } }
        public static string RecipeModal_UnknownIngredient { get { return ResourceManager.GetString("RecipeModal_UnknownIngredient", resourceCulture); } }
        public static string RecipeModal_AddSectionTitle { get { return ResourceManager.GetString("RecipeModal_AddSectionTitle", resourceCulture); } }
        public static string RecipeModal_ExistingIngredientLabel { get { return ResourceManager.GetString("RecipeModal_ExistingIngredientLabel", resourceCulture); } }
        public static string RecipeModal_SelectOrNewOption { get { return ResourceManager.GetString("RecipeModal_SelectOrNewOption", resourceCulture); } }
        public static string RecipeModal_AmountLabel { get { return ResourceManager.GetString("RecipeModal_AmountLabel", resourceCulture); } }
        public static string RecipeModal_AddBtn { get { return ResourceManager.GetString("RecipeModal_AddBtn", resourceCulture); } }
        public static string RecipeModal_CancelBtn { get { return ResourceManager.GetString("RecipeModal_CancelBtn", resourceCulture); } }
        public static string RecipeModal_NewIngredientBtn { get { return ResourceManager.GetString("RecipeModal_NewIngredientBtn", resourceCulture); } }
        public static string RecipeModal_NewCatalogTitle { get { return ResourceManager.GetString("RecipeModal_NewCatalogTitle", resourceCulture); } }
        public static string RecipeModal_NewIngNameLabel { get { return ResourceManager.GetString("RecipeModal_NewIngNameLabel", resourceCulture); } }
        public static string RecipeModal_NewIngNamePlaceholder { get { return ResourceManager.GetString("RecipeModal_NewIngNamePlaceholder", resourceCulture); } }
        public static string RecipeModal_NewIngUnitLabel { get { return ResourceManager.GetString("RecipeModal_NewIngUnitLabel", resourceCulture); } }
        public static string RecipeModal_NewIngSizeLabel { get { return ResourceManager.GetString("RecipeModal_NewIngSizeLabel", resourceCulture); } }
        public static string RecipeModal_NewIngPriceLabel { get { return ResourceManager.GetString("RecipeModal_NewIngPriceLabel", resourceCulture); } }
        public static string RecipeModal_CreateAndAssignBtn { get { return ResourceManager.GetString("RecipeModal_CreateAndAssignBtn", resourceCulture); } }
        public static string RecipeModal_Saving { get { return ResourceManager.GetString("RecipeModal_Saving", resourceCulture); } }

        // Ingredient modal keys
        public static string IngredientModal_TitleNew { get { return ResourceManager.GetString("IngredientModal_TitleNew", resourceCulture); } }
        public static string IngredientModal_TitleEdit { get { return ResourceManager.GetString("IngredientModal_TitleEdit", resourceCulture); } }
        public static string IngredientModal_NameLabel { get { return ResourceManager.GetString("IngredientModal_NameLabel", resourceCulture); } }
        public static string IngredientModal_UnitLabel { get { return ResourceManager.GetString("IngredientModal_UnitLabel", resourceCulture); } }
        public static string IngredientModal_PackageSizeLabel { get { return ResourceManager.GetString("IngredientModal_PackageSizeLabel", resourceCulture); } }
        public static string IngredientModal_PackagePriceLabel { get { return ResourceManager.GetString("IngredientModal_PackagePriceLabel", resourceCulture); } }
        public static string IngredientModal_PricePerUnitLabel { get { return ResourceManager.GetString("IngredientModal_PricePerUnitLabel", resourceCulture); } }

        // Fixed cost modal keys
        public static string FixedModal_Title { get { return ResourceManager.GetString("FixedModal_Title", resourceCulture); } }
        public static string FixedModal_DescPlaceholder { get { return ResourceManager.GetString("FixedModal_DescPlaceholder", resourceCulture); } }
        public static string FixedModal_AmountHeader { get { return ResourceManager.GetString("FixedModal_AmountHeader", resourceCulture); } }
        public static string FixedModal_AddPosition { get { return ResourceManager.GetString("FixedModal_AddPosition", resourceCulture); } }
        public static string FixedModal_Total { get { return ResourceManager.GetString("FixedModal_Total", resourceCulture); } }

        // Ingredients page keys
        public static string Ingredients_New { get { return ResourceManager.GetString("Ingredients_New", resourceCulture); } }
        public static string Ingredients_Loading { get { return ResourceManager.GetString("Ingredients_Loading", resourceCulture); } }
        public static string Ingredients_EmptyTitle { get { return ResourceManager.GetString("Ingredients_EmptyTitle", resourceCulture); } }
        public static string Ingredients_EmptyDesc { get { return ResourceManager.GetString("Ingredients_EmptyDesc", resourceCulture); } }
        public static string Ingredients_Name { get { return ResourceManager.GetString("Ingredients_Name", resourceCulture); } }
        public static string Ingredients_Unit { get { return ResourceManager.GetString("Ingredients_Unit", resourceCulture); } }
        public static string Ingredients_PackageSize { get { return ResourceManager.GetString("Ingredients_PackageSize", resourceCulture); } }
        public static string Ingredients_PackagePrice { get { return ResourceManager.GetString("Ingredients_PackagePrice", resourceCulture); } }
        public static string Ingredients_PricePerUnit { get { return ResourceManager.GetString("Ingredients_PricePerUnit", resourceCulture); } }
        public static string Ingredients_Actions { get { return ResourceManager.GetString("Ingredients_Actions", resourceCulture); } }

        // Info modal
        public static string InfoModal_Title { get { return ResourceManager.GetString("InfoModal_Title", resourceCulture); } }

        // Event planner keys
        public static string Event_Title { get { return ResourceManager.GetString("Event_Title", resourceCulture); } }
        public static string Event_New { get { return ResourceManager.GetString("Event_New", resourceCulture); } }
        public static string Event_SavedLabel { get { return ResourceManager.GetString("Event_SavedLabel", resourceCulture); } }
        public static string Event_NewUnsavedOption { get { return ResourceManager.GetString("Event_NewUnsavedOption", resourceCulture); } }
        public static string Event_Section1Title { get { return ResourceManager.GetString("Event_Section1Title", resourceCulture); } }
        public static string Event_NameLabel { get { return ResourceManager.GetString("Event_NameLabel", resourceCulture); } }
        public static string Event_GuestCount { get { return ResourceManager.GetString("Event_GuestCount", resourceCulture); } }
        public static string Event_DrinksPerGuest { get { return ResourceManager.GetString("Event_DrinksPerGuest", resourceCulture); } }
        public static string Event_FreeDrinks { get { return ResourceManager.GetString("Event_FreeDrinks", resourceCulture); } }
        public static string Event_FreeDrinksHint { get { return ResourceManager.GetString("Event_FreeDrinksHint", resourceCulture); } }
        public static string Event_WasteBuffer { get { return ResourceManager.GetString("Event_WasteBuffer", resourceCulture); } }
        public static string Event_Section2Title { get { return ResourceManager.GetString("Event_Section2Title", resourceCulture); } }
        public static string Event_FixedCosts { get { return ResourceManager.GetString("Event_FixedCosts", resourceCulture); } }
        public static string Event_FixedCostsHint { get { return ResourceManager.GetString("Event_FixedCostsHint", resourceCulture); } }
        public static string Event_PersonnelCosts { get { return ResourceManager.GetString("Event_PersonnelCosts", resourceCulture); } }
        public static string Event_PersonnelCostsHint { get { return ResourceManager.GetString("Event_PersonnelCostsHint", resourceCulture); } }
        public static string Event_TargetProfit { get { return ResourceManager.GetString("Event_TargetProfit", resourceCulture); } }
        public static string Event_TargetProfitHint { get { return ResourceManager.GetString("Event_TargetProfitHint", resourceCulture); } }

        // Recipes & search
        public static string Recipes_New { get { return ResourceManager.GetString("Recipes_New", resourceCulture); } }
        public static string Recipes_Loading { get { return ResourceManager.GetString("Recipes_Loading", resourceCulture); } }
        public static string Recipes_EmptyTitle { get { return ResourceManager.GetString("Recipes_EmptyTitle", resourceCulture); } }
        public static string Recipes_EmptyDesc { get { return ResourceManager.GetString("Recipes_EmptyDesc", resourceCulture); } }
        public static string Recipes_FirstNew { get { return ResourceManager.GetString("Recipes_FirstNew", resourceCulture); } }
        public static string Search_Placeholder { get { return ResourceManager.GetString("Search_Placeholder", resourceCulture); } }
        public static string Search_TopResults { get { return ResourceManager.GetString("Search_TopResults", resourceCulture); } }
        public static string Search_OtherResults { get { return ResourceManager.GetString("Search_OtherResults", resourceCulture); } }

        // More Event-related keys
        public static string Event_Section3Title { get { return ResourceManager.GetString("Event_Section3Title", resourceCulture); } }
        public static string Event_DistributeEvenly { get { return ResourceManager.GetString("Event_DistributeEvenly", resourceCulture); } }
        public static string Event_NoRecipesWarning { get { return ResourceManager.GetString("Event_NoRecipesWarning", resourceCulture); } }
        public static string Event_ShareLabel { get { return ResourceManager.GetString("Event_ShareLabel", resourceCulture); } }
        public static string Event_TotalDistribution { get { return ResourceManager.GetString("Event_TotalDistribution", resourceCulture); } }
        public static string Event_MustBe100 { get { return ResourceManager.GetString("Event_MustBe100", resourceCulture); } }
        public static string Event_CalculateBtn { get { return ResourceManager.GetString("Event_CalculateBtn", resourceCulture); } }
        public static string Event_NoCalculationYet { get { return ResourceManager.GetString("Event_NoCalculationYet", resourceCulture); } }
        public static string Event_NoCalculationHint { get { return ResourceManager.GetString("Event_NoCalculationHint", resourceCulture); } }
        public static string Event_ResultPrefix { get { return ResourceManager.GetString("Event_ResultPrefix", resourceCulture); } }
        public static string Event_PayingDrinksCount { get { return ResourceManager.GetString("Event_PayingDrinksCount", resourceCulture); } }
        public static string Event_ExportPdf { get { return ResourceManager.GetString("Event_ExportPdf", resourceCulture); } }
        public static string Event_MaterialCostTotal { get { return ResourceManager.GetString("Event_MaterialCostTotal", resourceCulture); } }
        public static string Event_TotalEventCosts { get { return ResourceManager.GetString("Event_TotalEventCosts", resourceCulture); } }
        public static string Event_TargetRevenue { get { return ResourceManager.GetString("Event_TargetRevenue", resourceCulture); } }
        public static string Event_AvgSalesPrice { get { return ResourceManager.GetString("Event_AvgSalesPrice", resourceCulture); } }
        public static string Event_CocktailCalcTitle { get { return ResourceManager.GetString("Event_CocktailCalcTitle", resourceCulture); } }
        public static string Event_TableCocktail { get { return ResourceManager.GetString("Event_TableCocktail", resourceCulture); } }
        public static string Event_TableShare { get { return ResourceManager.GetString("Event_TableShare", resourceCulture); } }
        public static string Event_TableCount { get { return ResourceManager.GetString("Event_TableCount", resourceCulture); } }
        public static string Event_TableRealPerDrink { get { return ResourceManager.GetString("Event_TableRealPerDrink", resourceCulture); } }
        public static string Event_TableRecommendedPrice { get { return ResourceManager.GetString("Event_TableRecommendedPrice", resourceCulture); } }
        public static string Event_CalcDisclaimer { get { return ResourceManager.GetString("Event_CalcDisclaimer", resourceCulture); } }
        public static string Event_ShoppingListTitle { get { return ResourceManager.GetString("Event_ShoppingListTitle", resourceCulture); } }
        public static string Event_TableIngredient { get { return ResourceManager.GetString("Event_TableIngredient", resourceCulture); } }
        public static string Event_TableDemand { get { return ResourceManager.GetString("Event_TableDemand", resourceCulture); } }
        public static string Event_TablePackage { get { return ResourceManager.GetString("Event_TablePackage", resourceCulture); } }
        public static string Event_TableTotalCost { get { return ResourceManager.GetString("Event_TableTotalCost", resourceCulture); } }

        // Many additional members are used; define a generic accessor to avoid missing properties.
        // Consumers should use the strongly-typed properties above; for any missing property add it here.
        public static string GetString(string name) {
            return ResourceManager.GetString(name, resourceCulture) ?? string.Empty;
        }
    }
}
