//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CateringCalculator.UI.Resources.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CateringCalculator.UI.Resources.Internationalization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Button_Details {
            get {
                return ResourceManager.GetString("Button_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ø Verkaufspreis / Drink.
        /// </summary>
        internal static string Event_AvgSalesPrice {
            get {
                return ResourceManager.GetString("Event_AvgSalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Inkl. vollem Gebinde und anteiliger Berücksichtigung von Freigetränken. Empfohlener Verkaufspreis beinhaltet Wareneinsatz plus gewerblichen Fixkosten- und Gewinnaufschlag..
        /// </summary>
        internal static string Event_CalcDisclaimer {
            get {
                return ResourceManager.GetString("Event_CalcDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event jetzt kalkulieren.
        /// </summary>
        internal static string Event_CalculateBtn {
            get {
                return ResourceManager.GetString("Event_CalculateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocktail-Kalkulation &amp; Verkaufspreise.
        /// </summary>
        internal static string Event_CocktailCalcTitle {
            get {
                return ResourceManager.GetString("Event_CocktailCalcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichmäßig verteilen.
        /// </summary>
        internal static string Event_DistributeEvenly {
            get {
                return ResourceManager.GetString("Event_DistributeEvenly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks / Gast.
        /// </summary>
        internal static string Event_DrinksPerGuest {
            get {
                return ResourceManager.GetString("Event_DrinksPerGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Exportieren.
        /// </summary>
        internal static string Event_ExportPdf {
            get {
                return ResourceManager.GetString("Event_ExportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixkosten (€).
        /// </summary>
        internal static string Event_FixedCosts {
            get {
                return ResourceManager.GetString("Event_FixedCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miete, Müll, Pauschalen etc..
        /// </summary>
        internal static string Event_FixedCostsHint {
            get {
                return ResourceManager.GetString("Event_FixedCostsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigetränke (Stk.).
        /// </summary>
        internal static string Event_FreeDrinks {
            get {
                return ResourceManager.GetString("Event_FreeDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fließen als Kostentreiber in den Wareneinsatz..
        /// </summary>
        internal static string Event_FreeDrinksHint {
            get {
                return ResourceManager.GetString("Event_FreeDrinksHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Gäste.
        /// </summary>
        internal static string Event_GuestCount {
            get {
                return ResourceManager.GetString("Event_GuestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wareneinsatz (Gesamt).
        /// </summary>
        internal static string Event_MaterialCostTotal {
            get {
                return ResourceManager.GetString("Event_MaterialCostTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Muss 100% ergeben).
        /// </summary>
        internal static string Event_MustBe100 {
            get {
                return ResourceManager.GetString("Event_MustBe100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltungsname *.
        /// </summary>
        internal static string Event_NameLabel {
            get {
                return ResourceManager.GetString("Event_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Event.
        /// </summary>
        internal static string Event_New {
            get {
                return ResourceManager.GetString("Event_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Neues Event (nicht gespeichert) --.
        /// </summary>
        internal static string Event_NewUnsavedOption {
            get {
                return ResourceManager.GetString("Event_NewUnsavedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fülle links die Parameter aus und klicke auf &quot;Event jetzt kalkulieren&quot;..
        /// </summary>
        internal static string Event_NoCalculationHint {
            get {
                return ResourceManager.GetString("Event_NoCalculationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Kalkulation vorhanden.
        /// </summary>
        internal static string Event_NoCalculationYet {
            get {
                return ResourceManager.GetString("Event_NoCalculationYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Rezepte vorhanden. Bitte erst unter &quot;Rezepte&quot; Cocktails anlegen!.
        /// </summary>
        internal static string Event_NoRecipesWarning {
            get {
                return ResourceManager.GetString("Event_NoRecipesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zahlende Drinks.
        /// </summary>
        internal static string Event_PayingDrinksCount {
            get {
                return ResourceManager.GetString("Event_PayingDrinksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalkosten (€).
        /// </summary>
        internal static string Event_PersonnelCosts {
            get {
                return ResourceManager.GetString("Event_PersonnelCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtlohn Service/Bar..
        /// </summary>
        internal static string Event_PersonnelCostsHint {
            get {
                return ResourceManager.GetString("Event_PersonnelCostsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis:.
        /// </summary>
        internal static string Event_ResultPrefix {
            get {
                return ResourceManager.GetString("Event_ResultPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gespeichertes Event:.
        /// </summary>
        internal static string Event_SavedLabel {
            get {
                return ResourceManager.GetString("Event_SavedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Event-Parameter &amp; Mengen.
        /// </summary>
        internal static string Event_Section1Title {
            get {
                return ResourceManager.GetString("Event_Section1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Kosten &amp; Wunschgewinn.
        /// </summary>
        internal static string Event_Section2Title {
            get {
                return ResourceManager.GetString("Event_Section2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Cocktails auswählen.
        /// </summary>
        internal static string Event_Section3Title {
            get {
                return ResourceManager.GetString("Event_Section3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteil:.
        /// </summary>
        internal static string Event_ShareLabel {
            get {
                return ResourceManager.GetString("Event_ShareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatische Einkaufsliste.
        /// </summary>
        internal static string Event_ShoppingListTitle {
            get {
                return ResourceManager.GetString("Event_ShoppingListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechne die benötigten Zutaten, Gebinde, Fixkosten und Ziel-Verkaufspreise..
        /// </summary>
        internal static string Event_Subtitle {
            get {
                return ResourceManager.GetString("Event_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocktail.
        /// </summary>
        internal static string Event_TableCocktail {
            get {
                return ResourceManager.GetString("Event_TableCocktail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        internal static string Event_TableCount {
            get {
                return ResourceManager.GetString("Event_TableCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedarf (inkl. Puffer/Freidrinks).
        /// </summary>
        internal static string Event_TableDemand {
            get {
                return ResourceManager.GetString("Event_TableDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutat.
        /// </summary>
        internal static string Event_TableIngredient {
            get {
                return ResourceManager.GetString("Event_TableIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaufm. Gebinde.
        /// </summary>
        internal static string Event_TablePackage {
            get {
                return ResourceManager.GetString("Event_TablePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real / Drink*.
        /// </summary>
        internal static string Event_TableRealPerDrink {
            get {
                return ResourceManager.GetString("Event_TableRealPerDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empf. Verkaufspreis.
        /// </summary>
        internal static string Event_TableRecommendedPrice {
            get {
                return ResourceManager.GetString("Event_TableRecommendedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteil.
        /// </summary>
        internal static string Event_TableShare {
            get {
                return ResourceManager.GetString("Event_TableShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtkosten.
        /// </summary>
        internal static string Event_TableTotalCost {
            get {
                return ResourceManager.GetString("Event_TableTotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wunschgewinn (€).
        /// </summary>
        internal static string Event_TargetProfit {
            get {
                return ResourceManager.GetString("Event_TargetProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netto-Gewinnziel, das auf die zahlenden Drinks umgelegt wird..
        /// </summary>
        internal static string Event_TargetProfitHint {
            get {
                return ResourceManager.GetString("Event_TargetProfitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziel-Umsatz (inkl. Gewinn).
        /// </summary>
        internal static string Event_TargetRevenue {
            get {
                return ResourceManager.GetString("Event_TargetRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event-Planung &amp; Kalkulation.
        /// </summary>
        internal static string Event_Title {
            get {
                return ResourceManager.GetString("Event_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verteilung gesamt:.
        /// </summary>
        internal static string Event_TotalDistribution {
            get {
                return ResourceManager.GetString("Event_TotalDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtkosten (inkl. Fix/Pers).
        /// </summary>
        internal static string Event_TotalEventCosts {
            get {
                return ResourceManager.GetString("Event_TotalEventCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwund-Puffer (%).
        /// </summary>
        internal static string Event_WasteBuffer {
            get {
                return ResourceManager.GetString("Event_WasteBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Position hinzufügen.
        /// </summary>
        internal static string FixedModal_AddPosition {
            get {
                return ResourceManager.GetString("FixedModal_AddPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag (€).
        /// </summary>
        internal static string FixedModal_AmountHeader {
            get {
                return ResourceManager.GetString("FixedModal_AmountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standmiete.
        /// </summary>
        internal static string FixedModal_DefaultDescription {
            get {
                return ResourceManager.GetString("FixedModal_DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung / Posten.
        /// </summary>
        internal static string FixedModal_DescPlaceholder {
            get {
                return ResourceManager.GetString("FixedModal_DescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixkosten im Detail.
        /// </summary>
        internal static string FixedModal_Title {
            get {
                return ResourceManager.GetString("FixedModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtsumme Fixkosten:.
        /// </summary>
        internal static string FixedModal_Total {
            get {
                return ResourceManager.GetString("FixedModal_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name der Zutat.
        /// </summary>
        internal static string IngredientModal_NameLabel {
            get {
                return ResourceManager.GetString("IngredientModal_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebindepreis (€).
        /// </summary>
        internal static string IngredientModal_PackagePriceLabel {
            get {
                return ResourceManager.GetString("IngredientModal_PackagePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebindegröße ({0}).
        /// </summary>
        internal static string IngredientModal_PackageSizeLabel {
            get {
                return ResourceManager.GetString("IngredientModal_PackageSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errechneter Preis pro Einheit:.
        /// </summary>
        internal static string IngredientModal_PricePerUnitLabel {
            get {
                return ResourceManager.GetString("IngredientModal_PricePerUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutat bearbeiten.
        /// </summary>
        internal static string IngredientModal_TitleEdit {
            get {
                return ResourceManager.GetString("IngredientModal_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Zutat anlegen.
        /// </summary>
        internal static string IngredientModal_TitleNew {
            get {
                return ResourceManager.GetString("IngredientModal_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einheit.
        /// </summary>
        internal static string IngredientModal_UnitLabel {
            get {
                return ResourceManager.GetString("IngredientModal_UnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktionen.
        /// </summary>
        internal static string Ingredients_Actions {
            get {
                return ResourceManager.GetString("Ingredients_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lege deine erste Zutat mit Gebindegröße und Preis an, um Rezepte berechnen zu können..
        /// </summary>
        internal static string Ingredients_EmptyDesc {
            get {
                return ResourceManager.GetString("Ingredients_EmptyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Zutaten vorhanden.
        /// </summary>
        internal static string Ingredients_EmptyTitle {
            get {
                return ResourceManager.GetString("Ingredients_EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Ingredients_Name {
            get {
                return ResourceManager.GetString("Ingredients_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Zutat anlegen.
        /// </summary>
        internal static string Ingredients_New {
            get {
                return ResourceManager.GetString("Ingredients_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebindepreis.
        /// </summary>
        internal static string Ingredients_PackagePrice {
            get {
                return ResourceManager.GetString("Ingredients_PackagePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebindegröße.
        /// </summary>
        internal static string Ingredients_PackageSize {
            get {
                return ResourceManager.GetString("Ingredients_PackageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis / Einheit.
        /// </summary>
        internal static string Ingredients_PricePerUnit {
            get {
                return ResourceManager.GetString("Ingredients_PricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwalte Gebindegrößen und Preise für deine Kalkulationen..
        /// </summary>
        internal static string Ingredients_Subtitle {
            get {
                return ResourceManager.GetString("Ingredients_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutatenverwaltung.
        /// </summary>
        internal static string Ingredients_Title {
            get {
                return ResourceManager.GetString("Ingredients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einheit.
        /// </summary>
        internal static string Ingredients_Unit {
            get {
                return ResourceManager.GetString("Ingredients_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du diesen Eintrag wirklich unwiderruflich löschen?.
        /// </summary>
        internal static string Msg_DeleteConfirm {
            get {
                return ResourceManager.GetString("Msg_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventplanung.
        /// </summary>
        internal static string Nav_EventPlanner {
            get {
                return ResourceManager.GetString("Nav_EventPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutaten.
        /// </summary>
        internal static string Nav_Ingredients {
            get {
                return ResourceManager.GetString("Nav_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersicht.
        /// </summary>
        internal static string Nav_Overview {
            get {
                return ResourceManager.GetString("Nav_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezepte.
        /// </summary>
        internal static string Nav_Recipes {
            get {
                return ResourceManager.GetString("Nav_Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Position hinzufügen.
        /// </summary>
        internal static string PersonnelModal_AddPosition {
            get {
                return ResourceManager.GetString("PersonnelModal_AddPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        internal static string PersonnelModal_CountHeader {
            get {
                return ResourceManager.GetString("PersonnelModal_CountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicekraft.
        /// </summary>
        internal static string PersonnelModal_DefaultRole {
            get {
                return ResourceManager.GetString("PersonnelModal_DefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunden.
        /// </summary>
        internal static string PersonnelModal_HoursHeader {
            get {
                return ResourceManager.GetString("PersonnelModal_HoursHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to € / Std..
        /// </summary>
        internal static string PersonnelModal_RateHeader {
            get {
                return ResourceManager.GetString("PersonnelModal_RateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle / Position.
        /// </summary>
        internal static string PersonnelModal_RolePlaceholder {
            get {
                return ResourceManager.GetString("PersonnelModal_RolePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalkosten im Detail.
        /// </summary>
        internal static string PersonnelModal_Title {
            get {
                return ResourceManager.GetString("PersonnelModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtsumme Personal:.
        /// </summary>
        internal static string PersonnelModal_Total {
            get {
                return ResourceManager.GetString("PersonnelModal_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Hinzufügen.
        /// </summary>
        internal static string RecipeModal_AddBtn {
            get {
                return ResourceManager.GetString("RecipeModal_AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutat hinzufügen.
        /// </summary>
        internal static string RecipeModal_AddSectionTitle {
            get {
                return ResourceManager.GetString("RecipeModal_AddSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge ({0}).
        /// </summary>
        internal static string RecipeModal_AmountLabel {
            get {
                return ResourceManager.GetString("RecipeModal_AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string RecipeModal_CancelBtn {
            get {
                return ResourceManager.GetString("RecipeModal_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutat anlegen &amp; übernehmen.
        /// </summary>
        internal static string RecipeModal_CreateAndAssignBtn {
            get {
                return ResourceManager.GetString("RecipeModal_CreateAndAssignBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string RecipeModal_DescLabel {
            get {
                return ResourceManager.GetString("RecipeModal_DescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurze Beschreibung.
        /// </summary>
        internal static string RecipeModal_DescPlaceholder {
            get {
                return ResourceManager.GetString("RecipeModal_DescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge unten mindestens eine Zutat hinzu..
        /// </summary>
        internal static string RecipeModal_EmptyWarning {
            get {
                return ResourceManager.GetString("RecipeModal_EmptyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existierende Zutat.
        /// </summary>
        internal static string RecipeModal_ExistingIngredientLabel {
            get {
                return ResourceManager.GetString("RecipeModal_ExistingIngredientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutaten des Rezeptes.
        /// </summary>
        internal static string RecipeModal_IngredientsHeader {
            get {
                return ResourceManager.GetString("RecipeModal_IngredientsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Cocktails *.
        /// </summary>
        internal static string RecipeModal_NameLabel {
            get {
                return ResourceManager.GetString("RecipeModal_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z. B. Mojito, Caipirinha....
        /// </summary>
        internal static string RecipeModal_NamePlaceholder {
            get {
                return ResourceManager.GetString("RecipeModal_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Zutat im Katalog anlegen.
        /// </summary>
        internal static string RecipeModal_NewCatalogTitle {
            get {
                return ResourceManager.GetString("RecipeModal_NewCatalogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RecipeModal_NewIngNameLabel {
            get {
                return ResourceManager.GetString("RecipeModal_NewIngNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z. B. Rohrzucker.
        /// </summary>
        internal static string RecipeModal_NewIngNamePlaceholder {
            get {
                return ResourceManager.GetString("RecipeModal_NewIngNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis (€).
        /// </summary>
        internal static string RecipeModal_NewIngPriceLabel {
            get {
                return ResourceManager.GetString("RecipeModal_NewIngPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Zutat.
        /// </summary>
        internal static string RecipeModal_NewIngredientBtn {
            get {
                return ResourceManager.GetString("RecipeModal_NewIngredientBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebindegröße.
        /// </summary>
        internal static string RecipeModal_NewIngSizeLabel {
            get {
                return ResourceManager.GetString("RecipeModal_NewIngSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einheit.
        /// </summary>
        internal static string RecipeModal_NewIngUnitLabel {
            get {
                return ResourceManager.GetString("RecipeModal_NewIngUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichere....
        /// </summary>
        internal static string RecipeModal_Saving {
            get {
                return ResourceManager.GetString("RecipeModal_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Wählen oder neu anlegen --.
        /// </summary>
        internal static string RecipeModal_SelectOrNewOption {
            get {
                return ResourceManager.GetString("RecipeModal_SelectOrNewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion.
        /// </summary>
        internal static string RecipeModal_TableAction {
            get {
                return ResourceManager.GetString("RecipeModal_TableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        internal static string RecipeModal_TableAmount {
            get {
                return ResourceManager.GetString("RecipeModal_TableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutat.
        /// </summary>
        internal static string RecipeModal_TableIngredient {
            get {
                return ResourceManager.GetString("RecipeModal_TableIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezept bearbeiten.
        /// </summary>
        internal static string RecipeModal_TitleEdit {
            get {
                return ResourceManager.GetString("RecipeModal_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Rezept anlegen.
        /// </summary>
        internal static string RecipeModal_TitleNew {
            get {
                return ResourceManager.GetString("RecipeModal_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        internal static string RecipeModal_UnknownIngredient {
            get {
                return ResourceManager.GetString("RecipeModal_UnknownIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten / Drink:.
        /// </summary>
        internal static string Recipes_CostPerDrink {
            get {
                return ResourceManager.GetString("Recipes_CostPerDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicke oben auf &quot;Neues Rezept anlegen&quot;, um dein erstes Rezept zu erstellen..
        /// </summary>
        internal static string Recipes_EmptyDesc {
            get {
                return ResourceManager.GetString("Recipes_EmptyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Rezepte vorhanden.
        /// </summary>
        internal static string Recipes_EmptyTitle {
            get {
                return ResourceManager.GetString("Recipes_EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstes Rezept anlegen.
        /// </summary>
        internal static string Recipes_FirstNew {
            get {
                return ResourceManager.GetString("Recipes_FirstNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutaten:.
        /// </summary>
        internal static string Recipes_IngredientsHeader {
            get {
                return ResourceManager.GetString("Recipes_IngredientsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezepte werden geladen....
        /// </summary>
        internal static string Recipes_Loading {
            get {
                return ResourceManager.GetString("Recipes_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Rezept anlegen.
        /// </summary>
        internal static string Recipes_New {
            get {
                return ResourceManager.GetString("Recipes_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwalte hier deine Rezepturen und Zutatenmengen..
        /// </summary>
        internal static string Recipes_Subtitle {
            get {
                return ResourceManager.GetString("Recipes_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocktails &amp; Rezepte.
        /// </summary>
        internal static string Recipes_Title {
            get {
                return ResourceManager.GetString("Recipes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        internal static string Recipes_UnknownIngredient {
            get {
                return ResourceManager.GetString("Recipes_UnknownIngredient", resourceCulture);
            }
        }
    }
}
