// <auto-generated />
using System;
using System.Globalization;
using System.Resources;

namespace CateringCalculator.Resources
{
    public static class AppResourcesPdf
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    // Use the merged AppResources resource file as the single source of translations
                    resourceMan = new ResourceManager("CateringCalculator.Resources.Resources.Internationalization.AppResources", typeof(AppResourcesPdf).Assembly);
                }
                return resourceMan;
            }
        }

        public static CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Header_ResultTitle => ResourceManager.GetString("Header_ResultTitle", resourceCulture) ?? string.Empty;
        public static string Header_PayingDrinks => ResourceManager.GetString("Header_PayingDrinks", resourceCulture) ?? string.Empty;
        public static string Header_PayingAndFreeDrinks => ResourceManager.GetString("Header_PayingAndFreeDrinks", resourceCulture) ?? string.Empty;
        public static string Kpi_MaterialCost => ResourceManager.GetString("Kpi_MaterialCost", resourceCulture) ?? string.Empty;
        public static string Kpi_TotalCosts => ResourceManager.GetString("Kpi_TotalCosts", resourceCulture) ?? string.Empty;
        public static string Section_CocktailCalculation => ResourceManager.GetString("Section_CocktailCalculation", resourceCulture) ?? string.Empty;
        public static string Table_Recipe => ResourceManager.GetString("Table_Recipe", resourceCulture) ?? string.Empty;
        public static string Table_Share => ResourceManager.GetString("Table_Share", resourceCulture) ?? string.Empty;
        public static string Table_Count => ResourceManager.GetString("Table_Count", resourceCulture) ?? string.Empty;
        public static string Table_RealPerDrink => ResourceManager.GetString("Table_RealPerDrink", resourceCulture) ?? string.Empty;
        public static string Table_RecommendedPrice => ResourceManager.GetString("Table_RecommendedPrice", resourceCulture) ?? string.Empty;
        public static string Section_ShoppingList => ResourceManager.GetString("Section_ShoppingList", resourceCulture) ?? string.Empty;
        public static string Table_Checkbox => ResourceManager.GetString("Table_Checkbox", resourceCulture) ?? string.Empty;
        public static string Table_Ingredient => ResourceManager.GetString("Table_Ingredient", resourceCulture) ?? string.Empty;
        public static string Table_TotalNeeded => ResourceManager.GetString("Table_TotalNeeded", resourceCulture) ?? string.Empty;
        public static string Table_Package => ResourceManager.GetString("Table_Package", resourceCulture) ?? string.Empty;
        public static string Table_Costs => ResourceManager.GetString("Table_Costs", resourceCulture) ?? string.Empty;
    }
}
